version: 2
jobs:
  build-staging:
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - run: |
          git submodule sync
          npm install
          npm rebuild node-sass
          npm install -g grunt
          grunt deploy:en --site-config=stg --aws-key="${AWS_KEY}" --aws-secret="${AWS_SECRET}" --aws-region="" --aws-bucket="s.monaca.io"
          grunt deploy:ja --site-config=stg --aws-key="${AWS_KEY}" --aws-secret="${AWS_SECRET}" --aws-region="" --aws-bucket="s.ja.monaca.io"

  build-production:
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - run: |
          git submodule sync
          npm install
          npm rebuild node-sass
          npm install -g grunt
          grunt deploy:en --aws-key="${AWS_KEY}" ---aws-secret="${AWS_SECRET}" --aws-region="" --aws-bucket="monaca.io"
          grunt deploy:ja --aws-key="${AWS_KEY}" ---aws-secret="${AWS_SECRET}" --aws-region="ap-northeast-1" --aws-bucket="ja.monaca.io"
          wget https://api.keycdn.com/zones/purge/38818.json --user="${KEY_CDN_API_KEY}" --password='' -v
          wget https://api.keycdn.com/zones/purge/38816.json --user="${KEY_CDN_API_KEY}" --password='' -v

workflows:
  version: 2
  publish:
    jobs:
      - build-staging:
          filters:
            branches:
              only:
                - master
      - build-production:
          filters:
            branches:
              only:
                - production
